ARG COMPRESSOR_IMAGE="docker.io/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d"
ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2024-09-01@sha256:0ed9a29bf734a13325b951ffbd169ed99aa9164172928081ff0779e05669ca92"

FROM ${COMPRESSOR_IMAGE} AS compressor
ARG UPX_INSTALLATION_COMMAND="apk add \
    libgcc=13.2.1_git20240309-r0 \
    libstdc++=13.2.1_git20240309-r0 \
    upx=4.2.4-r0 \
  && rm -rf /var/cache/apt/*"
ARG UPX_COMPRESSION_MODE="--fast"

USER root
WORKDIR /project
RUN eval "${UPX_INSTALLATION_COMMAND}"
COPY \
  --chmod=700 \
  target/*-runner /project/application
RUN upx \
  "${UPX_COMPRESSION_MODE}" \
  -o application-compressed \
  application

FROM ${DISTROLESS_IMAGE} as runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
# Include if the project has .so that need to be copied:
# COPY \
#  --chmod=444 \
#  target/*.so /lib/
COPY \
  --from=compressor \
  --chmod=111 \
   /project/application-compressed ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]
