ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2025-03-26@sha256:9a9cbbc45fbc6dd41038eeacdee147448c1d27175f2bd50fab06a096f927f079"

FROM ${DISTROLESS_IMAGE} as runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
# Include if the project has .so that need to be copied:
# COPY \
#  --chmod=444 \
#  target/*.so /lib/
COPY \
  --chmod=111 \
   target/*-runner ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]
