ARG COMPRESSOR_IMAGE="docker.io/alpine:3.20.3@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a"
ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2024-11-10@sha256:30fee20af069e962650daead049a9750af2d62fad509ad86939894718f4447c1"

FROM ${COMPRESSOR_IMAGE} AS compressor
ARG UPX_INSTALLATION_COMMAND="apk add \
    libgcc=13.2.1_git20240309-r0 \
    libstdc++=13.2.1_git20240309-r0 \
    upx=4.2.4-r0 \
  && rm -rf /var/cache/apt/*"
ARG UPX_COMPRESSION_MODE="--fast"

USER root
WORKDIR /project
RUN eval "${UPX_INSTALLATION_COMMAND}"
COPY \
  --chmod=700 \
  target/*-runner /project/application
RUN upx \
  "${UPX_COMPRESSION_MODE}" \
  -o application-compressed \
  application

FROM ${DISTROLESS_IMAGE} as runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
# Include if the project has .so that need to be copied:
# COPY \
#  --chmod=444 \
#  target/*.so /lib/
COPY \
  --from=compressor \
  --chmod=111 \
   /project/application-compressed ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]
